### ISSUE TITLE
Schema is invalid against it's meta schema.

### ISSUE THREAD

**Issue by magicrobotmonkey** [kubos/command_definitions_schema#1]
Using the schema like:

```
with open("mt_command_definitions.schema.json") as readme:
    schema = json.load(readme)

jsonschema.validate(instance=commands, schema=schema)
```

I get the following exception:
```
Traceback (most recent call last):
  File "/Users/abassett/work/rogue/example-python-gateway/command_csv_to_json.py", line 49, in <module>
    validate(instance=commands, schema=schema)
  File "/Users/abassett/venvs/majortom/lib/python3.10/site-packages/jsonschema/validators.py", line 1059, in validate
    cls.check_schema(schema)
  File "/Users/abassett/venvs/majortom/lib/python3.10/site-packages/jsonschema/validators.py", line 204, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: [{'type': 'integer'}, {'type': 'integer'}] is not of type 'object', 'boolean'

Failed validating 'type' in metaschema['allOf'][0]['properties']['$defs']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['oneOf']['items']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:
    {'$defs': {'anchorString': {'pattern': '^[A-Za-z_][-A-Za-z0-9._]*$',
                                'type': 'string'},
               'uriReferenceString': {'format': 'uri-reference',
                                      'type': 'string'},
               'uriString': {'format': 'uri', 'type': 'string'}},
     '$dynamicAnchor': 'meta',
     '$id': 'https://json-schema.org/draft/2020-12/meta/core',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     '$vocabulary': {'https://json-schema.org/draft/2020-12/vocab/core': True},
     'properties': {'$anchor': {'$ref': '#/$defs/anchorString'},
                    '$comment': {'type': 'string'},
                    '$defs': {'additionalProperties': {'$dynamicRef': '#meta'},
                              'type': 'object'},
                    '$dynamicAnchor': {'$ref': '#/$defs/anchorString'},
                    '$dynamicRef': {'$ref': '#/$defs/uriReferenceString'},
                    '$id': {'$comment': 'Non-empty fragments not allowed.',
                            '$ref': '#/$defs/uriReferenceString',
                            'pattern': '^[^#]*#?$'},
                    '$ref': {'$ref': '#/$defs/uriReferenceString'},
                    '$schema': {'$ref': '#/$defs/uriString'},
                    '$vocabulary': {'additionalProperties': {'type': 'boolean'},
                                    'propertyNames': {'$ref': '#/$defs/uriString'},
                                    'type': 'object'}},
     'title': 'Core vocabulary meta-schema',
     'type': ['object', 'boolean']}

On schema['$defs']['field']['oneOf'][0]['properties']['range']['items']:
    [{'type': 'integer'}, {'type': 'integer'}]
```

**Comment by dmitrydwhite** [comment]
OK, it looks like Draft 2020-12 is no longer happy with the `"items"` keyword; [this PR](https://github.com/kubos/command_definitions_schema/pull/2) should fix. If you want to try validating with the schema at: https://raw.githubusercontent.com/kubos/command_definitions_schema/ensure-valid-for-2020-12/mt_command_definitions.schema.json and let me know if that works.

I did notice that the python `jsonschema.validate` gives me some slightly different errors than I would get when writing the schema in VS Code. LMK if you need examples of the errors/prompts VS Code gave versus what I got with the python `jsonschema.validate`.

Hope this helps!

**Comment by magicrobotmonkey** [comment]
Looks good thanks! and thanks for the quick turnaround
